#: include dashboard.kv
#: include firstscreen.kv

NavigationLayout:
    id: nav_layout
    ScreenManager:
        Screen:
            BoxLayout:
                MDToolbar:
                ScreenManager:
                    id: screen_manager
                    DashBoard:
                        id: dashboard
                        name: "dashboard"
                    FirstScreen:
                        id: first_screen
                        name: "first_screen"
    MDNavigationDrawer: